language: node_js
node_js:
  - node
  - lts/*
  - 10
  - 8
deploy:
  provider: npm
  email: mail@geraintwhite.co.uk
  api_key:
    secure: 4Qfcdr+1QVkDQrJdwhQXr/Z6Vv4zJTlF1zDgjLa0eQ8hAuFEJt4dkro8/q7DsVb/osIQMfYmidGhEaiDK+vhG0HZ3WczAy2awEtkjAsdPYKV3T4M0wDdmwJithpEAn7p/Ga97G7vJfVpO15hYVzSr87aaf1TCiIUAIS0sM7VgaMwtupHkNvSNsCooY63iwwMT3JvrccGspoyShh3aet7Wn3uQf4sIbAgxY0nzaocxQSRA32Rc/jxfnD3NPpVckRI7iMJcYK+2cG+elFNIuX3zRT0DHKbdaJlfF2qJYqscObYEwcvtG23WC4xXQc+wRUI7iDKKHEpn78EIzp5sN8sHQJ2FUdZBM2sYmsLIZmQXFlfWeEoUqMRy92lVdcNA/rSI75bxyBtGLKL8YQ7lkvhl+5xS6z509RJqB6mz/PzUXqn+CtOkhYpS0rmOUCpp49aLYcj5OwxgyE+4rt36CHzA+XnFXtjmFcywOHZQ6spAolmuKNr5pxcvhiCD7v9a17SJ9IfTJvbweFRmn0VHv2QstiLzQQS1yAS0rX+ddseuJYFrJ65UOklFFnCWIRbxmqlf3Zf1N+OIHTbxOy/5HGCFZXwrmt0bIzwv26jhe68licSKA8R3/0ZlT+RAkkdC53gVxnRMp1tpMbdcwR0lpSL1uiAA5DymErzSQEYMaiaA8M=
  on:
    tags: true
    repo: grit96/markdown-templator
